Fix duplicate id
...apparently introduced as a (copy/paste?) typo in
ab28d2cbdffe0e5c9a966fa5f7659a455a042663 "sf-exception.PythonPrint new method",
causing build failures like (<https://ci.libreoffice.org/job/lo_ubsan/2129/>)

> Error: Duplicated entry. ID = par_id201613654395537  LANG = en-US in File /home/tdf/lode/jenkins/workspace/lo_ubsan/helpcontent2/source/text/sbasic/shared/03/avail_release.xhp
> /home/tdf/lode/jenkins/workspace/lo_ubsan/solenv/gbuild/HelpTarget.mk:67: recipe for target '/home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/HelpTranslatePartTarget/de/helpcontent2/source/text/sbasic/shared/03/done' failed
> make[1]: *** [/home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/HelpTranslatePartTarget/de/helpcontent2/source/text/sbasic/shared/03/done] Error 255

Change-Id: Ib8a773b04d8df1ed62b4d5a5780de2b9e70f88ae