Error: Duplicated entry. ID = par_id3154286  LANG = en-US
in File .../helpcontent2/source/text/shared/02/01170102.xhp.  Introduced with
e54918ea208076c28dd2b2879f2aee3f280f81b3 "document new value -1 for BoundColumn
property of ListBox."  No idea if this is a proper fix, though.

Change-Id: I6f6ce7ab425b3120b0794f622ac9111a6ad8f025