Revert "tdf#155193 Do not deliver Help files with indexer=exclude"
This reverts commit 539abfa7c3bbc9f0b234402083c743890b965cf7.

Reason for revert: daily builds fail to build with errors like
ERROR: file '/home/tdf/lode/jenkins/workspace/lo_gerrit/tb/build_master/instdir/help/en-US/text/shared/autokorr/01000000.html' does not exist
See https://ci.libreoffice.org/job/lo_daily_tb_linux_dbg/654/console

Change-Id: I9d00fb2596b280bf09934dfc87db64feb8fe6a80
Reviewed-on: https://gerrit.libreoffice.org/c/help/+/155600
Tested-by: Jenkins
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>