Include help2.js not help.js
Otherwise, causes a

  ReferenceError: getParameterByName is not defined

when loading

  <file:///.../instdir/help/index.html?swriter/.uno:HelpIndex?Language=en-US&System=UNIX&Version=6.1>

in the browser.

Change-Id: I13cdd36e44859a74c9a1b4e3b020fed2f56edda0