Fix duplicate ID
...introduced by 175750251cc83397e714586617681414316adf57 "tdf#152127
Change order for Country/State", causing

> [HPX] de/helpcontent2/source/text/shared/optionen
> Error: Duplicated entry. ID = par_id3150441  LANG = en-US in File lo/core/helpcontent2/source/text/shared/optionen/01010100.xhp

Change-Id: I28fdbda5b90f235381998c80664c4eb74fcadf7f
Reviewed-on: https://gerrit.libreoffice.org/c/help/+/143074
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>