Fix duplicate hid
...introduced by 8e6c3462c929a8ac34609f461ddc68684558c1d0 "tdf#105034 add help
text for option Position cell reference with selection", causing build failures
like

> Error: Duplicated entry. ID = hd_id3146146  LANG = en-US in File .../core/helpcontent2/source/text/shared/optionen/01060300.xhp
> make[1]: *** [.../core/solenv/gbuild/HelpTarget.mk:68: .../core/workdir/HelpTranslatePartTarget/de/helpcontent2/source/text/shared/optionen/done] Error 255

Change-Id: I02cc9b99dac272b36e846edfe02a89a7b9fc4bbb